cloudhsm.clusterid=clusterId
cloudhsm.cafile=caPath
cloudhsm.ip=
cloudhsm.port=2223
cloudhsm.user=user
cloudhsm.password=password
cloudhsm.keystore.password=secret123
pkcs11ConfigPath=/opt/cloudhsm/lib/libcloudhsm_pkcs11.so